apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::048105619199:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::048105619199:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2JTBYB8MTPMK
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-13T21:40:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "841"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 57b16790-7dcf-11ea-b1e9-02b6dc0f02a0