apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::048105619199:role/eksctl-simple-jwt-appi-nodegroup-NodeInstanceRole-1AWFTY3E9KG62
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::048105619199:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-08T13:35:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "899"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 79be53ac-fb8f-4475-9be3-823548a2d8f3
