apiVersion: v1
kind: Service
metadata:
  name: simple-jwt-appi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: simple-jwt-appi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-appi
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: simple-jwt-appi
  template:
    metadata:
      labels:
        app: simple-jwt-appi
    spec:
      containers:
        - name: simple-jwt-appi
          image: CONTAINER_IMAGE
          # image: aws/codebuild/docker:17.09.0
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
